### ISSUE TITLE
Put Link Examle

### ISSUE THREAD

**Issue by natural** [nlf/riakpbc#10]
Hey,

I can't figure out how to set links with a `put` operation.  Any ideas or examples?  I set the links array in the request, but nothing is set.

Thanks for the nice and _fast_ client.

**Comment by natural** [comment]
Hah!  Figured it out.  The `links` array needs to go into the `content` hash, not in the parameters to `put`.  Coffee fragment:

```
    links = [
      {'tag': 'friend', 'bucket':'users', 'key':'alice'}
      ]

    content =
      value: JSON.stringify doc
      content_type: 'application/json'
      links: links

    request =
      bucket: cls.bucket
      key: @key()
      content: content

    client.put request, (reply)->
      callback null, reply
```

**Comment by nlf** [comment]
Thanks for bringing this up, it actually points out the complete and utter lack of documentation, which I opened a new issue for at #11
