### ISSUE TITLE
Update Counter Inconsistent, Errors with Negative Values

### ISSUE THREAD

**Issue by natural** [nlf/riakpbc#16]
The tests don't cover this, but there's some funk in `updateCounter` such that an `amount` of 1 increases the counter by 2.

Probably related, when the `amount` is negative, the client throws an error and does not update the counter value.

Verified expected behavior with the HTTP interface.

Console log:

```
> client.updateCounter({bucket:'test', key:'counter_x', returnvalue: true, amount:1}, console.log)
undefined
> { value: 1 }
> client.updateCounter({bucket:'test', key:'counter_x', returnvalue: true, amount:1}, console.log)
undefined
> { value: 3 }
```

And then:

```
> client.updateCounter({bucket:'test', key:'counter_x', returnvalue: true, amount:-1}, console.log)
undefined
> { errmsg: 'Error processing incoming message: error:badarg:[{protobuffs,decode_varint,
(snip)
```

**Comment by nlf** [comment]
This is due to protobuf.js not supporting sint64 properly as a data type. I've opened ticket nlf/protobuf.js#5 to track it there
