### ISSUE TITLE
Timout the connect function

### ISSUE THREAD

**Issue by awenger** [nlf/riakpbc#17]
Hi,
I just noticed the following:
If the server is not available no error is reported. The cb is never called. I think it would be a good idea to implement a kind of timeout guard. Something like: http://stackoverflow.com/a/8377810.

**Comment by awenger** [comment]
https://github.com/nlf/riakpbc/pull/18

**Comment by nlf** [comment]
I gave some feedback on your pull request. This is a good idea, though.

**Comment by nlf** [comment]
Merged #18, closes this
