### ISSUE TITLE
Integer (_int) secondary indexes/indices

### ISSUE THREAD

**Issue by nisaacson** [nlf/riakpbc#20]
Currently only string secondary index keys work in the client. It would be nice to be able to specify integer secondary index keys
# Desired Int key value

The following gives an error `Uncaught TypeError: Argument should be a String.`

``` javascript
var indexes = [
  { key: 'key1_int', value: 2 },
  { key: 'key2_int', value: 100 }
]
var options = { 
  bucket: 'test', 
  key: 'test-put-index-integer', 
  content: { 
    value: '{"test":"data"}', 
    content_type: 'application/json', 
    indexes: indexes 
  }, 
  return_body: true 
};
client.put(options, function (err, reply) {
  if(err) { throw err }
  console.dir(reply)
})
```
# String Workaround with incorrect order

A workaround is to just stringify the index values. This allows secondary index to be set in Riak. 

However when querying the keys come back in the wrong order. In the example below the key corresponding to the secondary index value of `'100'` comes back before the key for the secondary index value `'2'`

``` javascript
var indexes = [
  { key: 'key1_bin', value: '2' },
  { key: 'key2_bin', value: '100' }
]
var options = { 
  bucket: 'test', 
  key: 'test-put-index-string', 
  content: { 
    value: '{"test":"data"}', 
    content_type: 'application/json', 
    indexes: indexes 
  }, 
  return_body: true 
};
client.put(options, function (err, reply) {
  if(err) { throw err }
  console.dir(reply)
})
```

**Comment by nlf** [comment]
The first part about having to pass integers as strings is a definite issue - I'm working on that one. The second part, I'm not able to reproduce. It looks like the values are being saved and returned in the correct order to me.. Can you write a short test case that shows them coming back incorrectly?

**Comment by nisaacson** [comment]
This is no longer an issue with the dependency update.
