### ISSUE TITLE
Streams cannot be piped

### ISSUE THREAD

**Issue by nisaacson** [nlf/riakpbc#22]
# Current

The streaming interface is a great feature, but is incompatible with other node streams in its current implementation. 

``` javascript
var keyStream = client.getKeys({ bucket: 'test' }, true)

keyStream.on('data', function (err, reply) {
  console.log('batch of keys:', reply.keys);
});

var someWriteableStream = through() // any writeable stream here

keyStream.pipe(someWritableStream) // this breaks here
```
# Proposal

Replacing the `EventEmitter` with an actual readable/writeable stream would allow streaming output from riakpbc to be piped into other streams. The downside is this require a breaking api change in `riakpbc`. The `data` event callback in standard node.js style streams takes a single data parameter. The errors are instead handled via an `error` event on the stream itself

``` javascript
var keyStream = client.getKeys({ bucket: 'test' }, true)

// note only a single data parameter in the callback with no error object
keyStream.on('data', function (reply) {
  console.log('batch of keys:', reply.keys);
});

// handle errors via the 'error' event on the stream
keyStream.on('error', function(err) {
  console.log('got an error')
  console.dir(err)
})
var someWriteableStream = through() // any writeable stream here

keyStream.pipe(someWritableStream) // this would now work
```

I am thinking about implementing this but wanted to get other thoughts before making breaking api changes.

**Comment by nlf** [comment]
I completely agree with making this change. I've actually had it on my mental roadmap for some time now, but haven't had the chance to get to it. If you can make it work, please do. I think with that implementation and updated tests, we can call this a 1.0.

**Comment by nisaacson** [comment]
sounds good. I will get to it

**Comment by nisaacson** [comment]
Fixed in master
