### ISSUE TITLE
Make riak 2.0 branch

### ISSUE THREAD

**Issue by nlf** [nlf/riakpbc#46]
I started this, but it's definitely not done. Need to add all the new commands. This will get published as version 2.0.0 when it's complete.

**Comment by nisaacson** [comment]
:+1:

**Comment by nlf** [comment]
Note that this is pending #45 since that will get merged into the branch before completing it..

**Comment by nisaacson** [comment]
What is the status of this work? I am going to be doing more work with riak 2.0 and want to help get `riakpbc` ready as needed.

**Comment by oleksiyk** [comment]
I also started working on some CRDT commands with `riakpbc`. Actually https://github.com/nlf/riakproto/tree/riak2 has everything to add new commands. I wonder if `riakpbc` should offer helper methods for CRDT operations like `addToSet`, `removeFromSet`, etc instead of generic `updateDtype` (`DtUpdateReq` message)?

**Comment by nlf** [comment]
The `riak2` branch is up to date with master, but as far as I got was updating the riakproto package to use the .proto files from the 2.0.0 preview.

Should just be a matter of adding the new commands.

@oleksiyk the idea behind this particular library was to stay as low level as possible, so I'm leaning towards no on the helper methods. I _am_ however, working on a branch of [simpleriak](https://github.com/nlf/simpleriak) that will allow either http or pbc usage, and that is where helper methods like that should live. Progress has been somewhat slow there, but I'm planning on devoting more time to it likely this weekend.

**Comment by oleksiyk** [comment]
Yeah, thats fine.

**Comment by oleksiyk** [comment]
Are the names `updateDtype` and `fetchDtype` ok for the respective `DtUpdateReq` and `DtFetchReq`? If so I will PR data type methods and tests soon. Or I can change the names of course.

**Comment by nlf** [comment]
yeah, I think that's fine for now

**Comment by nisaacson** [comment]
Does the riak2 branch support bucket types? 
http://docs.basho.com/riak/2.0.0beta1/dev/references/protocol-buffers/store-object/

The `message RpbPutReq` now has an additional field `optional bytes type = 16`

I am guessing this needs to get added in here?
https://github.com/nlf/riakproto/blob/master/proto/riak_kv.proto#L71

**Comment by nlf** [comment]
This riak2 branch is using the riak2 branch of riakproto, which is here:

https://github.com/nlf/riakproto/blob/riak2/proto/riak_kv.proto#L88

Should be all set.
:)

**Comment by nisaacson** [comment]
awesome thanks

**Comment by nlf** [comment]
Yeah I almost closed this the other day, but decided to keep it open until the branch gets merged to master, which should be ready to go at the same time riak 2.0 is released..

Side note: anyone had a chance to play with the security features? I made it so the client will send a start tls packet when it first connects to see if it can upgrade, and does the upgrade automatically if possible, as well as auths the connection for you

**Comment by nlf** [comment]
Closing this in favor of the 2.0.0 milestone
