### ISSUE TITLE
convert vclocks to strings

### ISSUE THREAD

**Issue by nlf** [nlf/riakpbc#53]
It looks like HTTP vclocks are identical to base64 encoding the buffer that we currently return, might be nice to go ahead and convert the buffers to base64 strings so that they match up and make things simpler to inspect.

**Comment by oleksiyk** [comment]
I think you don't usually compare vclocks manually a lot and even when you do (debugging) buffer representation is still good enough. Converting them for each get/put operation will just add some performance penalty (well, small one) and no real benefit. I mean you would only need string representation during debugging.

**Comment by nlf** [comment]
The more I think about it, the more I think you're right. This is probably useful in few enough situations to not really warrant it being in the library. Closing...
