### ISSUE TITLE
connection pooling

### ISSUE THREAD

**Issue by creole** [nlf/riakpbc#54]
is connection pooling on the roadmap?

**Comment by nlf** [comment]
It is, actually. I hadn't opened an issue for it yet, but it's in the works.

**Comment by creole** [comment]
looking forward to it, thanks

**Comment by oleksiyk** [comment]
I thought connection pool can (or should) be a feature of a more high-level wrapper over riakpbc. Its actually just few lines with https://github.com/coopernurse/node-pool

**Comment by nlf** [comment]
That's a debate I've been having with myself for some time. Pooling will either end up here, or in simpleriak when I'm done with the integration there. We'll see which one ends up working better.

**Comment by countrodrigo** [comment]
Any update on this? We are once again interested on using riakpbc as the underlying riak pb library.

**Comment by nlf** [comment]
No update as I still haven't decided if that feature belongs in this module, or something higher level. I may just write a quick riakpbc-pool module and handle it there.

**Comment by nlf** [comment]
I started playing with this today, and I think this actually may need to end up being part of riakpbc proper.

The main issue I'm having is that pool libraries are all asynchronous, which means I can't acquire a client, and return a stream. I'd like for a pooled version of the module to be a drop in replacement for the regular module, and that's just not possible as is.

So, my current thought is we shift message specific state to the connection manager, and allow riakpbc to pool connection managers. This shouldn't be too many changes, and will allow riakpbc to continue working as it always has, just with the added option of pooling connections.

Thoughts? @oleksiyk any objections?

**Comment by oleksiyk** [comment]
No objections. I just feel that pooling is that sort of thing that can easily be done with a simple wrapper when you need it. But the riakpbc library will definitely benefit from the built-in pooling.

**Comment by phated** [comment]
Could something like https://github.com/hughsk/object-pool work?

**Comment by nlf** [comment]
Connection pooling now exists in v2.0.0

**Comment by countrodrigo** [comment]
Awesome! But you are not leveraging the pipelining support that Riak's protobuf interface has. In here (https://github.com/nlf/riakpbc/blob/master/index.js#L60) you acquire a new pb connection for each request, and only release it after the response comes back. That means that you are significantly under utilizing each pb connection.

Riak actually supports multiple in-flight requests over a single connection, which means less networking overhead, less connections, and a happier/more responsive Riak. If you immediately release the connection after your acquire it, you will get the effect I am talking about.

We actually had already written a wrapper around RiakPBC to do almost exactly what you have done, but with this change I am suggesting. Let me know what you think and I will send you a PR.

**Comment by nlf** [comment]
You're proposing just moving the release outside of the callback, so that the message is sent and the connection released immediately?

**Comment by countrodrigo** [comment]
Releasing immediately after the acquire callback comes back, rather than after receiving the Riak response in https://github.com/nlf/riakpbc/blob/master/index.js#L81.

Of course, this means that generic-pool will no longer know when a connection is being overloaded and thus won't create more connections than the low watermark. For generic-pool's high/low watermark mechanism to work you would need something like the maximum number of inflight requests that a single connection is allowed to handle.

**Comment by nlf** [comment]
Interesting. I'll look into implementing tracking of in-flight requests on a per connection basis. I definitely don't want to make the quick change that can cause a single connection to take on all the load, but this sounds like a good idea for a future iteration.

**Comment by countrodrigo** [comment]
I just heard back from Basho that they don't officially support pipelining, so even though the server seems to be able to support it, there is no guarantee on the order of responses and no way to reconcile requests with responses.

I misread this line 'Once connected the client can send a stream of requests on the same connection.' for pipelining support, when they really just mean it's a persistent TCP connection.

**Comment by nlf** [comment]
Good to know. Thanks for getting back to me!
