### ISSUE TITLE
Is there a plan to add Riak 2.0 security features?

### ISSUE THREAD

**Issue by dave-re** [nlf/riakpbc#65]
Hello, my name is kyu dong.
Is there a plan to add Riak 2.0 security(https://github.com/basho/riak/issues/355) features?

**Comment by nlf** [comment]
Yes there is. I haven't had time to see what changes need to be made yet, but we will definitely support security features.

**Comment by nlf** [comment]
Added automatic upgrading to tls sockets when available, as well as automatically authenticating if credentials are passed to the client constructor. That's about all that's required in the library side of things
