### ISSUE TITLE
Domains do not work

### ISSUE THREAD

**Issue by mde** [nlf/riakpbc#70]
Domains do not work with riakpbc -- errors in callbacks crash the process instead of being handled by the domain. Here's a minimal example:

https://gist.github.com/mde/5e01d8d5a46c0a8a9e0f

I'll submit a PR for this.

**Comment by nlf** [comment]
Merged your fix and published as v1.4.2 and v2.0.0-beta7

Out of curiosity, have you tested to see if domains work appropriately when using the returned streams? I'm assuming they will, but I haven't tried.

**Comment by mde** [comment]
I was assuming too. Might be worth checking, but at least the plain-vanilla error case works correctly now. Thanks for the merge!
