### ISSUE TITLE
Concurrency client pool bug

### ISSUE THREAD

**Issue by romulka** [nlf/riakpbc#79]
Hello.

If i use 1 client from createClient(), with 2 concurrency request, it's stops after 21 request. As i see, pool acquire connection, then release and acquire it again and do not release it.

Test case: https://gist.github.com/romulka/ca1ba0722f97911a7783

**Comment by nlf** [comment]
Published 2.0.2, should take care of this problem. Thanks for letting me know!

**Comment by romulka** [comment]
Yes, it works. Thanks.
