### ISSUE TITLE
Auto reconnect code is gone and closed sockets aren't handled cleanly

### ISSUE THREAD

**Issue by countrodrigo** [nlf/riakpbc#80]
I noticed the auto reconnect code is gone from the connection manager. Is this intentional?

This causes issues when the socket is closed by the server side (either on error or intentional close). I noticed it because I happened to have my idleTimeout set to a higher value than the haproxy's client idle timeout of 16 seconds, which meant that any connection that didn't see any activity would end up getting closed by haproxy. However the connection manager code still considers this client good and fails silently, since the disconnect() method doesn't really set any flags or take further action.

**Comment by nlf** [comment]
You're absolutely right, the connection should be removing itself from the pool in the event of a disconnect. I'll get it fixed.

**Comment by nlf** [comment]
Should be fixed in 2.0.3 release that I just published, let me know if this is still broken.

**Comment by countrodrigo** [comment]
Thanks for the quick fix. It seems to be working.
