### ISSUE TITLE
Program does not exit

### ISSUE THREAD

**Issue by sachshar** [nlf/riakpbc#85]
Hey,

I have used below code to get the keys of a bucket 'polls'.
-  -  -  -  -  -  -  -  -  -  -  -  -  CODE -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  
  var riakpbc = require('riakpbc');
  var client = riakpbc.createClient({host: 'localhost', port: 8087});

var keys = client.getKeys({ bucket: 'polls' });

keys.on('error', function (err) {
  console.error('An error occurred:', err);
});

keys.on('data', function (response) {
  console.log('Got some keys:', response.keys); // this could fire multiple times
});

keys.on('end', function () {
  console.log('Finished listing keys');
});
-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - OUTPUT -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  
  Got some keys: [ 'B5gd8ToUlhPK4n6m6WWEKvESPRz' ]

Got some keys: [ 'LRgoITzVQj5dEiPcC7TebFTzAXO' ]

Got some keys: [ 'ILXh5NX5x918rxdsT89A7qTkEHI' ]

Got some keys: [ 'FNYDkyCaCfyinTlTYxpl8W5uWWQ' ]

Got some keys: [ '7lueKK1owMsAVmjScRcB6MPtJ36' ]

Got some keys: [ 'SQ8e01lOeK5yjQXBlzuVXosiltS' ]

Got some keys: [ '8erOandd8GojAEDPbayWwMTF9Ww' ]

Finished listing keys

---

 When running this program, it lists the keys for me and properly displays the message 'Finished listing keys' but then it doesn't exit which i need. Is there any method available which should be called at end to explicitly end the program.
## 

Thanks.
Sachin

**Comment by nlf** [comment]
Calling `client.end()` will forcibly shut down the connection pool and allow your program to close.
